services:
  - type: web
    name: college-complaint-backend
    rootDir: backend
    plan: free
    runtime: docker
    buildCommand: ./mvnw -DskipTests package || mvn -DskipTests package
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: complaint-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: complaint-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: complaint-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: complaint-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: complaint-db
          property: password
      - key: FRONTEND_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false

databases:
  - name: complaint-db
    databaseName: college_complaint_portal
    user: complaint_user
    plan: free
